---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-clone
  namespace: tekton-pipelines
spec:
  workspaces:
    - name: output
      description: The git repo will be cloned onto the volume backing this Workspace.
  params:
    - name: url
      description: Repository URL to clone from.
      type: string
    - name: revision
      description: Revision to checkout. (branch, tag, sha, ref, etc...)
      type: string
      default: ""
  results:
    - name: commit
      description: The precise commit SHA that was fetched by this Task.
    - name: url
      description: The precise URL that was fetched by this Task.
  steps:
    - name: clone
      image: alpine/git
      script: |
        #!/usr/bin/env sh
        set -eu

        ssh-keyscan github.com >> /root/.ssh/known_hosts # very specific, may want to use known_hosts from secret instead
        cd $(workspaces.output.path)

        git clone --verbose $(params.url) project
        cd project
        RESULT_SHA="$(git rev-parse HEAD)"

        printf "%s" "${RESULT_SHA}" > "$(results.commit.path)"
        printf "%s" "$(params.url)" > "$(results.url.path)"
