resources:
  # pipeline
  - https://storage.googleapis.com/tekton-releases/pipeline/latest/release.yaml
  # dashboard
  - https://github.com/tektoncd/dashboard/releases/latest/download/tekton-dashboard-release.yaml
